name: Pipeline for test suite

on:
  push:
    branches: [main, development]

jobs:
  tests:
    strategy:
      matrix:
        # Operative systems allowed [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing depedencies
      run: make install

    - name: Run linter (Betty)
      run: make linter

    - name: Run test's suite
      run: make tests

    - name: Building proccess
      run: make build