name: Pipeline for test suite

on:
  push:
    branches: [main, development]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing depedencies
      run: make install

    - name: Run test's suite
      run: make tests
  betty:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing depedencies
      run: make install

    - name: Run linter (Betty)
      run: make linter
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing depedencies
      run: make install

    - name: Building proccess
      run: make build
